name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "unstable"
          spago: "unstable"
          purs-tidy: "latest"

      - uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/*.dhall') }}
          path: |
            .spago
            output

      - name: Install dependencies
        run: spago install

      - name: Build source
        run: spago build

      - name: Run tests
        run: spago test

      - name: Check formatting
        run: purs-tidy check src test

